m4_include([m4macros/alsa.m4])
m4_include([m4macros/binreloc.m4])
m4_include([m4macros/detectcflags.m4])
m4_include([m4macros/gimpprint.m4])
m4_include([m4macros/pythondev.m4])
m4_include([m4macros/ax_cxx_compile_stdcxx.m4])
